#ifndef CMDLIME_SHORTMACROS_H
#define CMDLIME_SHORTMACROS_H

#include "detail/configmacros.h"

#define PARAM CMDLIME_PARAM
#define PARAMLIST CMDLIME_PARAMLIST
#define FLAG CMDLIME_FLAG
#define EXITFLAG CMDLIME_EXITFLAG
#define ARG CMDLIME_ARG
#define ARGLIST CMDLIME_ARGLIST
#define COMMAND CMDLIME_COMMAND
#define SUBCOMMAND CMDLIME_SUBCOMMAND

#endif //CMDLIME_SHORTMACROS_H