#pragma once
#include "detail/configmacro.h"

#define PARAM CMDLIME_PARAM
#define PARAMLIST CMDLIME_PARAMLIST
#define FLAG CMDLIME_FLAG
#define EXITFLAG CMDLIME_EXITFLAG
#define ARG CMDLIME_ARG
#define ARGLIST CMDLIME_ARGLIST
#define COMMAND CMDLIME_COMMAND
#define SUBCOMMAND CMDLIME_SUBCOMMAND
