name: build & test (clang, gcc, MSVC)

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "master", "dev" ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: ${{ matrix.config.name }} (nameof = ${{ matrix.use_nameof }})
    runs-on: ${{ matrix.config.os }}
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    strategy:
      fail-fast: false
      matrix:
        use_nameof: ["ON", "OFF"]
        config:
          - {
            name: "Ubuntu Latest gcc",
            os: ubuntu-latest,
            cmake-preset: "gcc-release"
          }
          - {
            name: "Ubuntu Latest clang",
            os: ubuntu-latest,
            cmake-preset: "clang-release"
          }
          - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            cmake-preset: "msvc-release"
          }
    steps:
    - name: Install ninja (Windows)
      if: matrix.config.os == 'windows-latest'
      run: choco install ninja
    - name: Install ninja (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      run: sudo apt install ninja-build

    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: hendrikmuhs/ccache-action@v1.2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DENABLE_TESTS=ON -DENABLE_EXAMPLES=ON -DCMDLIME_USE_NAMEOF=${{ matrix.use_nameof }} --preset="${{ matrix.config.cmake-preset }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

